CREATE DATABASE BANCO_DE_DAD0S_ESCOLA;

CREATE TABLE ALUNO(
    ID INT,
    NOME VARCHAR,
    E-MAIL VARCHAR,
    ENDERECO VARCHAR,
    TELEFONE VARCHAR,
    PRIMARY KEY (ID)
);
/*
CREATE TABLE EMPRESTIMO(
    CODIGO INT,
    DATA_HORA DATETIME,
    MATRIC_ALUNO INT,
    DATA_DEVOLUCAO DATE
);
CREATE TABLE LIVRO_EMPRESTIMO(
    COD_LIVRO INT,
    COD_EMPRESTIMO INT
);
CREATE TABLE LIVRO(
    COD_LIVRO INT,
    TITULO VARCHAR,
    AUTOR VARCHAR,
    COD_SESSAO INT
);
CREATE TABLE SESSAO (
    CODIGO INT,
    DESCRICAO VARCHAR,
    LOCALIZACAO VARCHAR
);*/